// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjIUlvy2SmljH362uCsxW4pAYw0i9c9Yo',
    appId: '1:798635139551:android:b04a1befe4d6b4afb2646a',
    messagingSenderId: '798635139551',
    projectId: 'ossvideo-5e684',
    databaseURL: 'https://ossvideo-5e684-default-rtdb.firebaseio.com',
    storageBucket: 'ossvideo-5e684.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBc7FX8gLFZWeCcfxt9pftAXwWyMzwdG48',
    appId: '1:798635139551:ios:1d072c4ac31ad90bb2646a',
    messagingSenderId: '798635139551',
    projectId: 'ossvideo-5e684',
    databaseURL: 'https://ossvideo-5e684-default-rtdb.firebaseio.com',
    storageBucket: 'ossvideo-5e684.appspot.com',
    iosClientId: '798635139551-fu7ol3i3mu95saruprmjorkh7brkfno3.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterStore',
  );
}
